#!/bin/bash

echo "Name of project:"
read project

test -z $project && exit 1
PDIR=../$project

mkdir $PDIR
cp -r * $PDIR

cd $PDIR
# rename dirs
mv NAME $project
mv tests/NAME_tests.py tests/${project}_tests.py

# replace instances of NAME in code
for f in setup.py tests/${project}_tests.py
do
  sed -i "s/NAME/$project/g" $f
done
