#!/bin/bash

usage() {
  echo "Usage: $0 project_name" >&2
}

project="$1"
test -z $project && usage && exit 1
PDIR=../$project

mkdir $PDIR
cp -r NAME/ tests/ setup.py $PDIR

cd $PDIR
# rename dirs
touch README
mv NAME $project
mv tests/NAME_tests.py tests/${project}_tests.py

# replace instances of NAME in code
for f in setup.py tests/${project}_tests.py
do
  sed -i "s/NAME/$project/g" $f
done
